version: '3.8'

services:
  brewlytics:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ../Cafe_Rewards_Offers:/app/Cafe_Rewards_Offers
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
